define(function(require,exports,module){var e=require("./zepto");var j=require("./utils/parseTpl");var f=require("./utils/highlight");var k=require("./utils/gmu");
var m=require("./utils/event");var c=require("./utils/widget");require("./utils/touch");require("./utils/dialog");require("./utils/$position");var a="index.php?act=goods&op=comments&goods_id="+SEADATA.goods_id+"&id="+SEADATA.store_id;
h(a);e("#s-buy-open").change(function(s){p();});var n=e(".goods-detail header li");var d=0;n.on("tap",function(t){var s=e(this).index();q(n,e(this),s);
});e(window).resize(function(){q(n,n.first(),0);});e("#direct-buy").on("tap",function(){i("buynow");});e("#add-cart").on("tap",function(){i("");});function h(s){e("#review-list").load(s,function(){e("#review-list").find("a.btn").on("tap",function(){var t=e(this).attr("href");
if(!e(this).hasClass("disabled")){h(t);}return false;});e("#review-list").find("select.btn").change(function(){var t=e(this).val();h(t);});});}function q(s,A,y){s.removeClass("current");
A.addClass("current");var D=y-d;var w=e(".scroller").width();e(".scroller").children().css("width",w+"px");if(D==0){return;}var v=0-d*w;var u=0-y*w;var B=v;
var z=D>0?0-(w/10):w/10;var C=setInterval(function(){B=B+z;if(D>0&&B<u||D<0&&B>u){B=u;}e(".scroller").css("-webkit-transform","translate3d("+B+"px, 0, 0)");
console.info("目标位置："+u+";当前位置："+B);if(B==u){clearInterval(C);d=y;}},20);}e("#increase").on("tap",function(){var s=parseInt(e("#num").val());if(isNaN(s)){s=0;
}o(s+1);});e("#decrease").on("tap",function(){var s=parseInt(e("#num").val());if(isNaN(s)){s=0;}o(s-1);});e("#num").on("blur",function(){var s=parseInt(e(this).val());
if(isNaN(s)){s=0;}o(s);});function p(){var s=e("#s-buy-open").attr("checked");console.info("打开状态："+s);if(s==true){e("#goods-buy").addClass("open");}else{e("#goods-buy").removeClass("open");
}}function o(s){if(s<=0){s=1;}e("#num").val(s);}function g(s,u,t){switch(t){case"buynow":url="index.php?act=buynow&buynow_spec_id="+s+"&buynow_quantity="+u;
break;case"groupbuy":url="index.php?act=show_groupbuy&op=groupbuy_buy&group_id="+SEADATA.group_id+"&groupbuy_spec_id="+s+"&groupbuy_quantity="+u;break;
}window.location.href=url;}function b(s,u){var t="index.php?act=cart&op=add&spec_id="+s+"&quantity="+u;e.getJSON(t,function(v){if(v!=null){if(v.done){l("添加购物成功");
}else{r(v.msg);}}});}function i(w){var t=0;var x=document.getElementsByName("specInput1");var v=document.getElementsByName("specInput2");for(var u=0;u<x.length;
u++){if(x[u].checked){t++;}}for(var u=0;u<v.length;u++){if(v[u].checked){t++;}}if(goodsspec.getSpec()==null||t<SEADATA.spec_count){e("#goods-buy").addClass("open");
r("请选择相关规格");return;}var s=goodsspec.getSpec().id;var y=parseInt(document.getElementById("num").value);if(!y>=1){r("请填写购买数量");document.getElementById("num").value=1;
return;}max=parseInt(document.getElementById("goods_stock").value);if(y>max){r("您购买的商品数量，超出了该商品库存，请您重新选择商品数量");return;}switch(w){case"groupbuy":g(s,y,"groupbuy");
break;case"buynow":g(s,y,"buynow");break;default:b(s,y);break;}}function r(s){e("#J-message").html(s);e("#J-message").dialog({autoOpen:false,closeBtn:false,buttons:{"确定":function(){this.close();
},}});e("#J-message").dialog("open");}function l(s){e("#J-success-msg").html(s);e("#J-success-msg").dialog({autoOpen:false,closeBtn:false,buttons:{"继续购物":function(){this.close();
},"查看购物车":function(){window.location.href="index.php?act=cart";this.close();}}});e("#J-success-msg").dialog("open");}});