define(function(require,exports,module){var c=require("./gmu");var b=c.$;var d=b.fx.cssPrefix,a=b.fx.transitionEnd;c.define("Panel",{options:{contentWrap:"",scrollMode:"follow",display:"push",position:"right",dismissible:true,swipeClose:true},_init:function(){var f=this,e=f._options;
f.on("ready",function(){f.displayFn=f._setDisplay();f.$contentWrap.addClass("ui-panel-animate");f.$el.on(a,b.proxy(f._eventHandler,f)).hide();e.dismissible&&f.$panelMask.hide().on("click",b.proxy(f._eventHandler,f));
e.scrollMode!=="follow"&&b(window).on("scrollStop",b.proxy(f._eventHandler,f));b(window).on("ortchange",b.proxy(f._eventHandler,f));});},_create:function(){if(this._options.setup){var g=this,f=g._options,e=g.$el.addClass("ui-panel ui-panel-"+f.position);
g.panelWidth=e.width()||0;g.$contentWrap=b(f.contentWrap||e.next());f.dismissible&&(g.$panelMask=b('<div class="ui-panel-dismiss"></div>').width(document.body.clientWidth-e.width()).appendTo("body")||null);
}else{throw new Error("panel组件不支持create模式，请使用setup模式");}},_setDisplay:function(){var i=this,k=i.$el,f=i.$contentWrap,e=d+"transform",l=i._transDisplayToPos(),j={},h,g;
b.each(["push","overlay","reveal"],function(m,n){j[n]=function(p,q,o){h=l[n].panel,g=l[n].cont;k.css(e,"translate3d("+i._transDirectionToPos(q,h[p])+"px,0,0)");
if(!o){f.css(e,"translate3d("+i._transDirectionToPos(q,g[p])+"px,0,0)");i.maskTimer=setTimeout(function(){i.$panelMask&&i.$panelMask.css(q,k.width()).toggle(p);
},400);}return i;};});return j;},_initPanelPos:function(e,f){this.displayFn[e](0,f,true);this.$el.get(0).clientLeft;return this;},_transDirectionToPos:function(f,e){return f==="left"?e:-e;
},_transDisplayToPos:function(){var e=this,f=e.panelWidth;return{push:{panel:[-f,0],cont:[0,f]},overlay:{panel:[-f,0],cont:[0,0]},reveal:{panel:[0,0],cont:[0,f]}};
},_setShow:function(g,h,n){var m=this,f=m._options,l=g?"open":"close",o=b.Event("before"+l),k=g!==m.state(),e=g?"on":"off",i=g?b.proxy(m._eventHandler,m):m._eventHandler,j=h||f.display,p=n||f.position;
m.trigger(o,[h,n]);if(o.isDefaultPrevented()){return m;}if(k){m._dealState(g,j,p);m.displayFn[j](m.isOpen=Number(g),p);f.swipeClose&&m.$el[e](b.camelCase("swipe-"+p),i);
f.display=j,f.position=p;}return m;},_dealState:function(f,h,k){var i=this,e=i._options,l=i.$el,g=i.$contentWrap,m="ui-panel-"+h+" ui-panel-"+k,j="ui-panel-"+e.display+" ui-panel-"+e.position+" ui-panel-animate";
if(f){l.removeClass(j).addClass(m).show();e.scrollMode==="fix"&&l.css("top",b(window).scrollTop());i._initPanelPos(h,k);if(h==="reveal"){g.addClass("ui-panel-contentWrap").on(a,b.proxy(i._eventHandler,i));
}else{g.removeClass("ui-panel-contentWrap").off(a,b.proxy(i._eventHandler,i));l.addClass("ui-panel-animate");}i.$panelMask&&i.$panelMask.css({left:"auto",right:"auto",height:document.body.clientHeight});
}return i;},_eventHandler:function(i){var h=this,g=h._options,j=g.scrollMode,f=h.state()?"open":"close";switch(i.type){case"click":case"swipeLeft":case"swipeRight":h.close();
break;case"scrollStop":j==="fix"?h.$el.css("top",b(window).scrollTop()):h.close();break;case a:h.trigger(f,[g.display,g.position]);break;case"ortchange":h.$panelMask&&h.$panelMask.css("height",document.body.clientHeight);
j==="fix"&&h.$el.css("top",b(window).scrollTop());break;}},open:function(f,e){return this._setShow(true,f,e);},close:function(){return this._setShow(false);
},toggle:function(f,e){return this[this.isOpen?"close":"open"](f,e);},state:function(){return !!this.isOpen;},destroy:function(){this.$panelMask&&this.$panelMask.off().remove();
this.maskTimer&&clearTimeout(this.maskTimer);this.$contentWrap.removeClass("ui-panel-animate");b(window).off("scrollStop",this._eventHandler);b(window).off("ortchange",this._eventHandler);
return this.$super("destroy");}});});