define(function(require,exports,module){var i=require("./gmu");var f=i.$;var l=[].slice,m=Object.prototype.toString,p=function(){},d=["options","template","tpl2html"],e=(function(){var s={},u=0,t="_gid";
return function(y,x,z){var v=y[t]||(y[t]=++u),w=s[v]||(s[v]={});z!==undefined&&(w[x]=z);z===null&&delete w[x];return w[x];};})(),n=i.event;function h(s){return m.call(s)==="[object Object]";
}function j(t,s){t&&Object.keys(t).forEach(function(u){s(u,t[u]);});}function c(t){try{t=t==="true"?true:t==="false"?false:t==="null"?null:+t+""===t?+t:/(?:\{[\s\S]*\}|\[[\s\S]*\])$/.test(t)?JSON.parse(t):t;
}catch(s){t=undefined;}return t;}function g(w){var u={},t=w&&w.attributes,s=t&&t.length,v,x;while(s--){x=t[s];v=x.name;if(v.substring(0,5)!=="data-"){continue;
}v=v.substring(5);x=c(x.value);x===undefined||(u[v]=x);}return u;}function k(t){var u=t.substring(0,1).toLowerCase()+t.substring(1),s=f.fn[u];f.fn[u]=function(x){var w=l.call(arguments,1),z=typeof x==="string"&&x,v,y;
f.each(this,function(A,B){y=e(B,t)||new i[t](B,h(x)?x:undefined);if(z==="this"){v=y;return false;}else{if(z){if(!f.isFunction(y[z])){throw new Error("组件没有此方法："+z);
}v=y[z].apply(y,w);if(v!==undefined&&v!==y){return false;}v=undefined;}}});return v!==undefined?v:this;};f.fn[u].noConflict=function(){f.fn[u]=s;return this;
};}function a(s,u){var t=this;if(s.superClass){a.call(t,s.superClass,u);}j(e(s,"options"),function(v,w){w.forEach(function(y){var z=y[0],x=y[1];if(z==="*"||(f.isFunction(z)&&z.call(t,u[v]))||z===u[v]){x.call(t);
}});});}function r(s,u){var t=this;if(s.superClass){r.call(t,s.superClass,u);}j(e(s,"plugins"),function(v,w){if(u[v]===false){return;}j(w,function(x,z){var y;
if(f.isFunction(z)&&(y=t[x])){t[x]=function(){var A=t.origin,B;t.origin=y;B=z.apply(t,arguments);A===undefined?delete t.origin:(t.origin=A);return B;};
}else{t[x]=z;}});w._init.call(t);});}function o(){var s=l.call(arguments),t=s.length,u;while(t--){u=u||s[t];h(s[t])||s.splice(t,1);}return s.length?f.extend.apply(null,[true,{}].concat(s)):u;
}function b(u,s,v,w,t){var y=this,x;if(h(w)){t=w;w=undefined;}t&&t.el&&(w=f(t.el));w&&(y.$el=f(w),w=y.$el[0]);x=y._options=o(s.options,g(w),t);y.template=o(s.template,x.template);
y.tpl2html=o(s.tpl2html,x.tpl2html);y.widgetName=u.toLowerCase();y.eventNs="."+y.widgetName+v;y._init(x);y._options.setup=(y.$el&&y.$el.parent()[0])?true:false;
a.call(y,s,x);r.call(y,s,x);y._create();y.trigger("ready");w&&e(w,u,y)&&y.on("destroy",function(){e(w,u,null);});return y;}function q(v,u,x){if(typeof x!=="function"){x=i.Base;
}var w=1,t=1;function s(z,y){if(v==="Base"){throw new Error("Base类不能直接实例化");}if(!(this instanceof s)){return new s(z,y);}return b.call(this,v,s,w++,z,y);
}f.extend(s,{register:function(z,A){var y=e(s,"plugins")||e(s,"plugins",{});A._init=A._init||p;y[z]=A;return s;},option:function(z,A,B){var y=e(s,"options")||e(s,"options",{});
y[z]||(y[z]=[]);y[z].push([A,B]);return s;},inherits:function(y){return q(v+"Sub"+t++,y,s);},extend:function(A){var z=s.prototype,y=x.prototype;d.forEach(function(B){A[B]=o(x[B],A[B]);
A[B]&&(s[B]=A[B]);delete A[B];});j(A,function(B,C){if(typeof C==="function"&&y[B]){z[B]=function(){var E=this.$super,D;this.$super=function(){var F=l.call(arguments,1);
return y[B].apply(this,F);};D=C.apply(this,arguments);E===undefined?(delete this.$super):(this.$super=E);return D;};}else{z[B]=C;}});}});s.superClass=x;
s.prototype=Object.create(x.prototype);s.extend(u);return s;}i.define=function(t,s,u){i[t]=q(t,s,u);k(t);};i.isWidget=function(t,s){s=typeof s==="string"?i[s]||p:s;
s=s||i.Base;return t instanceof s;};i.Base=q("Base",{_init:p,_create:p,getEl:function(){return this.$el;},on:n.on,one:n.one,off:n.off,trigger:function(u){var s=typeof u==="string"?new i.Event(u):u,t=[s].concat(l.call(arguments,1)),w=this._options[s.type],v=this.getEl();
if(w&&f.isFunction(w)){false===w.apply(this,t)&&(s.stopPropagation(),s.preventDefault());}n.trigger.apply(this,t);v&&v.triggerHandler(s,(t.shift(),t));
return this;},tpl2html:function(u,t){var s=this.template;s=typeof u==="string"?s[u]:((t=u),s);return t||~s.indexOf("<%")?f.parseTpl(s,t):s;},destroy:function(){this.$el&&this.$el.off(this.eventNs);
this.trigger("destroy");this.off();this.destroyed=true;}},Object);f.ui=i;});